#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (c) 2007 洪任諭 (PCMan) <pcman.tw@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os, urllib, os.path, re, sys

base = 'http://hichannel.hinet.net/player/radio/index.jsp?radio_id='
url = base + sys.argv[1]

dir_path = os.path.expanduser('~/.config/hinedo/' )

def download( url ):
    class Downloader( urllib.FancyURLopener ):
        version = 'Windows Media Player'
    f = Downloader().open( url )
    if f:
        content = f.read()
        f.close()
        return content
    return ''

page = download( url )
reg = re.compile( '(mms://.*?)(&|")', re.I|re.M )
match = reg.search( page )
url = match.group(1)
url=url.replace('mms://','http://')
os.execl( '/usr/bin/mplayer', 'mplayer', '-prefer-ipv4', '-cache', '32',url)
print 'Error: cannot execute player.'
