#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright (c) 2007 洪任諭 (PCMan) <pcman.tw@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import os, urllib, os.path, xml.dom.minidom

dir_path = os.path.expanduser('~/.config/hinedo/' )

def download( url ):
    class Downloader( urllib.FancyURLopener ):
        version = 'Windows Media Player'
    f = Downloader().open( url )
    if f:
        content = f.read()
        f.close()
        return content
    return ''

try:
    f = open( dir_path + 'menu', 'wb' )
except:
    exit(1)

menu = download('http://hichannel.hinet.net/xml/radioList.jsp');
dom = xml.dom.minidom.parseString(menu);

for tag in dom.getElementsByTagName('tag'):
    line = "%s\n" % tag.getAttribute('_title')
    f.write( line.encode('UTF-8', 'UTF-8') )
    for item in tag.getElementsByTagName('item'):
        line = "%s\t%s\n" % (item.getAttribute('myTitle'), item.getAttribute('id'))
        f.write( line.encode('UTF-8', 'UTF-8') )
    f.write('\n')
